/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getMessagesByChatId } from '../fn/message/get-messages-by-chat-id';
import { GetMessagesByChatId$Params } from '../fn/message/get-messages-by-chat-id';
import { MessageResponse } from '../models/message-response';
import { saveMessage } from '../fn/message/save-message';
import { SaveMessage$Params } from '../fn/message/save-message';
import { setMessagesToSeen } from '../fn/message/set-messages-to-seen';
import { SetMessagesToSeen$Params } from '../fn/message/set-messages-to-seen';
import { uploadMessage } from '../fn/message/upload-message';
import { UploadMessage$Params } from '../fn/message/upload-message';

@Injectable({ providedIn: 'root' })
export class MessageService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `saveMessage()` */
  static readonly SaveMessagePath = '/api/v1/messages';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveMessage()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveMessage$Response(params: SaveMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = saveMessage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveMessage$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveMessage(params: SaveMessage$Params, context?: HttpContext): Observable<void> {
    const resp = this.saveMessage$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `setMessagesToSeen()` */
  static readonly SetMessagesToSeenPath = '/api/v1/messages';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setMessagesToSeen()` instead.
   *
   * This method doesn't expect any request body.
   */
  setMessagesToSeen$Response(params: SetMessagesToSeen$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = setMessagesToSeen(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setMessagesToSeen$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  setMessagesToSeen(params: SetMessagesToSeen$Params, context?: HttpContext): Observable<void> {
    const resp = this.setMessagesToSeen$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `uploadMessage()` */
  static readonly UploadMessagePath = '/api/v1/messages/upload-media';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadMessage()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadMessage$Response(params: UploadMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = uploadMessage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadMessage$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadMessage(params: UploadMessage$Params, context?: HttpContext): Observable<void> {
    const resp = this.uploadMessage$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getMessagesByChatId()` */
  static readonly GetMessagesByChatIdPath = '/api/v1/messages/chat/{chatId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMessagesByChatId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMessagesByChatId$Response(params: GetMessagesByChatId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MessageResponse>>> {
    const obs = getMessagesByChatId(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMessagesByChatId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMessagesByChatId(params: GetMessagesByChatId$Params, context?: HttpContext): Observable<Array<MessageResponse>> {
    const resp = this.getMessagesByChatId$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<MessageResponse>>): Array<MessageResponse> => r.body)
    );
  }

}
